# Generated by Django 4.0.5 on 2022-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0005_alter_stock_vaccine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
