# Generated by Django 4.0.5 on 2022-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0006_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_facility', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('Date', models.DateField(auto_now=True)),
                ('vaccine_name', models.CharField(blank=True, choices=[('BCG', 'BCG'), ('DPT-HepB-Hib', 'DPT-HepB-Hib'), ('OPV', 'OPV'), ('IPV', 'IPV'), ('Rotavirus vaccine', 'Rotavirus vaccine'), ('Yellow Fever', 'Yellow Fever'), ('Measles Rubella', 'Measles Rubella'), ('PCV', 'PCV'), ('HPV', 'HPV'), ('Tetanus Toxiod diptheria(Td)', 'Tetanus Toxiod diptheria(Td)')], max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('dosed_given_out', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
