# Generated by Django 4.0.5 on 2022-11-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0007_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vaccines_control.stock'),
        ),
    ]
