# Generated by Django 4.0.5 on 2022-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0008_alter_issue_issue_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
