# Generated by Django 4.0.5 on 2022-11-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0009_alter_issue_issue_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='dosed_given_out',
            new_name='doses_given_to_other_facilities',
        ),
    ]
