# Generated by Django 4.0.5 on 2022-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0010_rename_dosed_given_out_issue_doses_given_to_other_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='vaccine_name',
            field=models.CharField(blank=True, choices=[('BCG', 'BCG'), ('DPT-HepB-Hib', 'DPT-HepB-Hib'), ('OPV', 'OPV'), ('IPV', 'IPV'), ('Rotavirus vaccine', 'Rotavirus vaccine'), ('Yellow Fever', 'Yellow Fever'), ('Measles Rubella', 'Measles Rubella'), ('PCV', 'PCV'), ('HPV', 'HPV'), ('Tetanus Toxiod diptheria(Td)', 'Tetanus Toxiod diptheria(Td)'), ('0.05mls', '0.05mls'), ('0.5mls', '0.5mls'), ('2mls', '2mls'), ('5mls', '5mls'), ('0.1mls', '0.1mls'), ('Mabendazole', 'Mabendazole'), ('Vitamin A 200,000iu', 'Vitamin A 200,000iu'), ('Vitamin A 100,000iu', 'Vitamin A 100,000iu'), ('Albendazole', 'Albendazole')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='vaccine_name',
            field=models.CharField(blank=True, choices=[('BCG', 'BCG'), ('DPT-HepB-Hib', 'DPT-HepB-Hib'), ('OPV', 'OPV'), ('IPV', 'IPV'), ('Rotavirus vaccine', 'Rotavirus vaccine'), ('Yellow Fever', 'Yellow Fever'), ('Measles Rubella', 'Measles Rubella'), ('PCV', 'PCV'), ('HPV', 'HPV'), ('Tetanus Toxiod diptheria(Td)', 'Tetanus Toxiod diptheria(Td)'), ('0.05mls', '0.05mls'), ('0.5mls', '0.5mls'), ('2mls', '2mls'), ('5mls', '5mls'), ('0.1mls', '0.1mls'), ('Mabendazole', 'Mabendazole'), ('Vitamin A 200,000iu', 'Vitamin A 200,000iu'), ('Vitamin A 100,000iu', 'Vitamin A 100,000iu'), ('Albendazole', 'Albendazole')], max_length=50, null=True),
        ),
    ]
