# Generated by Django 4.0.5 on 2022-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccines_control', '0011_alter_issue_vaccine_name_alter_stock_vaccine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number_vaccinated',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
